/*
 * This source file was generated by the Gradle 'init' task
 */
package tips.hw;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import org.junit.jupiter.api.Test;
import tips.hw.services.BonusService;
import tips.hw.services.impl.BonusServiceImpl;

class BonusServiceTest {
    @Test
    void calculateBonusPointsForNormalAmount() {
        BonusService service = new BonusServiceImpl();

        assertEquals(1, service.calculateBonusPoints(100));
    }

    @Test
    void calculateBonusPointsForNegativeAmount() {
        BonusService service = new BonusServiceImpl();

        assertThrows(IllegalArgumentException.class, () -> {
            service.calculateBonusPoints(-1.0);
        });
    }

    @Test
    void calculateBonusPointsForZeroAmount() {
        BonusService service = new BonusServiceImpl();

        assertEquals(0, service.calculateBonusPoints(0.0));
    }

    @Test
    void calculateBonusPointsForDecimalAmount() {
        BonusService service = new BonusServiceImpl();

        assertEquals(9, service.calculateBonusPoints(999.9));
    };

    @Test
    void calculateBonusPointsForUnder100() {
        BonusService service = new BonusServiceImpl();

        assertEquals(0, service.calculateBonusPoints(90));
    };
}
