/*
 * This source file was generated by the Gradle 'init' task
 */
package junit.basics.hw;

import junit.basics.hw.discount.DiscountCalculator;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import org.junit.jupiter.api.Test;

class DiscountCalculatorTest {
    @Test
    void testNormal() {
        assertEquals(0.9, DiscountCalculator.calculate(1.0, 0.1));
    }

    @Test
    void testZero() {
        assertEquals(1.0, DiscountCalculator.calculate(1.0, 0.0));
    }

    @Test
    void testNegative() {
        assertThrows(IllegalArgumentException.class, () -> {
            DiscountCalculator.calculate(1.0, -0.1);
        });
    }

    @Test
    void testOverflow() {
        assertThrows(IllegalArgumentException.class, () -> {
            DiscountCalculator.calculate(1.0, 1.1);
        });
    }

    @Test
    void testFullDiscount() {
        assertEquals(0.0, DiscountCalculator.calculate(1.0, 1.0));
    }
}
