/*
 * This source file was generated by the Gradle 'init' task
 */
package module.hw;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.Optional;
import module.hw.exceptions.OrderNotFoundException;
import module.hw.model.Order;
import module.hw.repository.OrderRepository;
import module.hw.repository.impl.OrderRepositoryInMemory;
import module.hw.service.OrderService;
import module.hw.service.impl.OrderServiceImpl;
import org.junit.jupiter.api.Test;

class OrderFlowTest {

  @Test
  void processOrderShouldReturnOrderIdWhenOrderIsProcessed() {
    OrderRepository orderRepositoryMock = mock(OrderRepositoryInMemory.class);

    OrderService orderService = new OrderServiceImpl(orderRepositoryMock);
    Order order = new Order(1, "Product 1", 3, 100.0);

    when(orderRepositoryMock.saveOrder(order)).thenReturn(1);

    orderService.processOrder(order);
    verify(orderRepositoryMock, times(1)).saveOrder(order);
    assertEquals(
      "Order processed successfully, orderId: " + 1,
      orderService.processOrder(order)
    );
  }

  @Test
  void processOrderShouldThrowExceptionWhenIncorrectOrder() {
    OrderRepository orderRepositoryMock = mock(OrderRepositoryInMemory.class);
    OrderService orderService = new OrderServiceImpl(orderRepositoryMock);
    Order order = new Order(-1, "Product 1", 3, 100.0);

    when(orderRepositoryMock.saveOrder(order)).thenThrow(
      IllegalArgumentException.class
    );

    assertThrows(IllegalArgumentException.class, () ->
      orderService.processOrder(order)
    );
    verify(orderRepositoryMock, times(1)).saveOrder(order);
  }

  @Test
  void calculateTotalPriceShouldReturnCorrectTotal() {
    OrderRepository orderRepositoryMock = mock(OrderRepository.class);
    OrderService orderService = new OrderServiceImpl(orderRepositoryMock);

    Order order = new Order(1, "Product 1", 3, 100.0);

    when(orderRepositoryMock.findOrderById(1)).thenReturn(Optional.of(order));
    double total = orderService.calculateTotal(order.getId());

    assertEquals(300.0, total, 0.01);
    verify(orderRepositoryMock, times(1)).findOrderById(1);
  }

  @Test
  void calculateTotalPriceShouldThrowExceptionWhenOrderNotFound() {
    OrderRepository orderRepositoryMock = mock(OrderRepository.class);
    OrderService orderService = new OrderServiceImpl(orderRepositoryMock);

    when(orderRepositoryMock.findOrderById(1)).thenReturn(Optional.empty());

    assertThrows(OrderNotFoundException.class, () ->
      orderService.calculateTotal(1)
    );
    verify(orderRepositoryMock, times(1)).findOrderById(1);
  }

  @Test
  void calculateTotalPriceShouldThrowExceptionWhenIncorrectOrderId() {
    OrderRepository orderRepositoryMock = mock(OrderRepository.class);
    OrderService orderService = new OrderServiceImpl(orderRepositoryMock);

    when(orderRepositoryMock.findOrderById(-1)).thenThrow(
      new IllegalArgumentException("Id cannot be negative")
    );

    assertThrows(IllegalArgumentException.class, () ->
      orderService.calculateTotal(-1)
    );
    verify(orderRepositoryMock, times(1)).findOrderById(-1);
  }
}
