/*
 * This source file was generated by the Gradle 'init' task
 */
package mockito.hw;

import mockito.hw.services.NotificationService;
import mockito.hw.services.OrderService;
import mockito.hw.services.PaymentService;
import mockito.hw.services.impl.OrderServiceImpl;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.Test;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

class OrderServiceTests {
    @Test
    void createOrderShouldReturnTrueWhenPaymentSuccessfull() {
        PaymentService paymentServiceMock = mock(PaymentService.class);
        NotificationService notificationServiceMock = mock(NotificationService.class);

        OrderService orderService = new OrderServiceImpl(paymentServiceMock, notificationServiceMock);

        when(paymentServiceMock.makePayment(100.0)).thenReturn(true);

        boolean result = orderService.placeOrder(100.0);

        assertTrue(result);
    }

    @Test
    void createOrderShouldSendNotificationWhenPaymentSuccessfull() {
        PaymentService paymentServiceMock = mock(PaymentService.class);
        NotificationService notificationServiceMock = mock(NotificationService.class);

        OrderService orderService = new OrderServiceImpl(paymentServiceMock, notificationServiceMock);

        when(paymentServiceMock.makePayment(1.0)).thenReturn(true);

        orderService.placeOrder(1.0);

        verify(notificationServiceMock).sendNotification("Order was successfully created");
    }

    @Test
    void createOrderShouldReturnFalseWhenPaymentFailed() {
        PaymentService paymentServiceMock = mock(PaymentService.class);
        NotificationService notificationServiceMock = mock(NotificationService.class);

        OrderService orderService = new OrderServiceImpl(paymentServiceMock, notificationServiceMock);

        when(paymentServiceMock.makePayment(1.0)).thenReturn(false);

        boolean result = orderService.placeOrder(1.0);

        assertEquals(false, result);
    }

    @Test
    void createOrderShouldNotSendNotificationWhenPaymentFailed() {
        PaymentService paymentServiceMock = mock(PaymentService.class);
        NotificationService notificationServiceMock = mock(NotificationService.class);

        OrderService orderService = new OrderServiceImpl(paymentServiceMock, notificationServiceMock);

        when(paymentServiceMock.makePayment(1.0)).thenReturn(false);

        orderService.placeOrder(1.0);

        verify(notificationServiceMock, times(0)).sendNotification("Order was successfully created");
    }

    @Test
    void createOrderShouldThrowErrorWhenAmountIsNegative() {
        PaymentService paymentServiceMock = mock(PaymentService.class);
        NotificationService notificationServiceMock = mock(NotificationService.class);

        OrderService orderService = new OrderServiceImpl(paymentServiceMock, notificationServiceMock);

        assertThrows(IllegalArgumentException.class, () -> {
            orderService.placeOrder(-1.0);
        });
    }
}
